export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const RELATED_PRODUCTS = "RELATED_PRODUCTS";
export const AVERAGE_RATING = "AVERAGE_RATING";
export const LOAD_STYLES = "LOAD_STYLES";
export const SELECT_STYLE = "SELECT_STYLE";

export const LOAD_OVERALL_DATA = "LOAD_OVERALL_DATA";